jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: git submodule update --init
  - script: ./build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: bin/artifacts/

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: git submodule update --init
  - script: ./build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: bin/artifacts/

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: git submodule update --init
  - script: .\ci_build.bat
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: bin/artifacts/
